# Generated by Django 5.1.3 on 2024-11-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP_app', '0002_sparepart_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='qr_pdf',
            field=models.FileField(blank=True, upload_to='qr_pdfs'),
        ),
    ]
