# Generated by Django 5.1.3 on 2024-12-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP_app', '0004_bill_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
