# Generated by Django 5.1.3 on 2024-12-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP_app', '0006_alter_supplier_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
