# Generated by Django 5.1.3 on 2025-02-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP_app', '0009_verivcationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verivcationtoken',
            name='reset_password_expires',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='verivcationtoken',
            name='reset_password_token',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
