# Generated by Django 5.1.3 on 2025-02-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP_app', '0010_alter_verivcationtoken_reset_password_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verivcationtoken',
            name='reset_password_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verivcationtoken',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
