# Generated by Django 5.1.3 on 2025-03-07 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP_app', '0011_alter_verivcationtoken_reset_password_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='CSP_app.supplier'),
        ),
        migrations.CreateModel(
            name='IncomeBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_bills', to='CSP_app.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='sparepart',
            name='income_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='CSP_app.incomebill'),
        ),
    ]
