# Generated by Django 5.1.3 on 2025-03-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP_app', '0012_alter_sparepart_supplier_incomebill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomebill',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
