# Generated by Django 5.1.3 on 2025-03-07 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP_app', '0013_alter_incomebill_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CSP_app.incomebill')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSP_app.sparepart')),
            ],
        ),
    ]
