# Generated by Django 5.1.3 on 2025-08-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP_app', '0015_sparepart_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
