# Generated by Django 5.1.3 on 2025-08-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP_app', '0016_sparepart_date_alter_sparepart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
