# Generated by Django 5.1.3 on 2025-08-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP_app', '0017_alter_sparepart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomebill',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
