# Generated by Django 5.1.3 on 2025-08-10 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP_app', '0018_incomebill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomebillitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_bill_items', to='CSP_app.category'),
        ),
        migrations.AddField(
            model_name='incomebillitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomebillitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incomebillitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='incomebillitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_bill_items', to='CSP_app.supplier'),
        ),
        migrations.AlterField(
            model_name='incomebillitem',
            name='spare_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_bill_items', to='CSP_app.sparepart'),
        ),
        migrations.AlterField(
            model_name='incomebillitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
