# Generated by Django 5.1.3 on 2025-08-10 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSP_app', '0019_incomebillitem_category_incomebillitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomebillitem',
            name='supplier',
        ),
    ]
