# Generated by Django 5.1.3 on 2025-08-10 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSP_app', '0020_remove_incomebillitem_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='income_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spare_parts', to='CSP_app.incomebill'),
        ),
    ]
